"""Config layer: workspace/config.yaml (non-secret) + .env (secrets).

Layout:
    workspace/
    ├── config.yaml      # model name, channels list, agent_name (NO secrets)
    ├── .env             # OPENAI_API_KEY, TELEGRAM_BOT_TOKEN, etc.
    ├── SOUL.md
    ├── IDENTITY.md
    ├── USER.md
    ├── MEMORY.md
    └── skills/

Secrets NEVER go in config.yaml. Channels reference secrets by *env var name*
(``secret: OPENAI_API_KEY``) which is resolved at runtime.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False


# ---------- model ----------

@dataclass
class ModelConfig:
    provider: str = "openai"          # openai | anthropic | custom
    base_url: str = "https://api.openai.com/v1"
    api_key_env: str = "OPENAI_API_KEY"
    model: str = "gpt-4o-mini"
    temperature: float = 0.7
    max_tokens: int = 4096

    def resolved_api_key(self) -> str:
        return os.environ.get(self.api_key_env, "")


# ---------- channel ----------

@dataclass
class ChannelConfig:
    type: str                          # telegram | discord | slack | ...
    name: str                          # unique handle for this channel instance
    enabled: bool = True
    secret_env: str = ""               # env var name holding the token (e.g. TELEGRAM_BOT_TOKEN)
    options: dict[str, Any] = field(default_factory=dict)

    def resolved_token(self) -> str:
        return os.environ.get(self.secret_env, "") if self.secret_env else ""


# ---------- root config ----------

@dataclass
class AppConfig:
    agent_name: str = "my-agent"
    model: ModelConfig = field(default_factory=ModelConfig)
    channels: list[ChannelConfig] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "agent_name": self.agent_name,
            "model": asdict(self.model),
            "channels": [asdict(c) for c in self.channels],
        }

    @classmethod
    def from_dict(cls, d: dict) -> "AppConfig":
        m = d.get("model") or {}
        channels = [ChannelConfig(**c) for c in (d.get("channels") or [])]
        return cls(
            agent_name=d.get("agent_name", "my-agent"),
            model=ModelConfig(**m),
            channels=channels,
        )

    def channel(self, name: str) -> ChannelConfig | None:
        for c in self.channels:
            if c.name == name:
                return c
        return None


# ---------- .env ----------

ENV_LINE_RE = re.compile(r"^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$")


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a .env file into a dict. Supports quoted values and # comments."""
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = ENV_LINE_RE.match(line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ('"', "'"):
            v = v[1:-1]
        out[k] = v
    return out


def write_env_file(path: Path, values: dict[str, str], overwrite: bool = False) -> None:
    """Write .env. If overwrite=False, only writes keys not already set."""
    existing = parse_env_file(path) if path.exists() else {}
    if overwrite:
        existing = {}
    existing.update(values)
    lines = ["# Generated by my-agent CLI", ""]
    for k in sorted(existing):
        v = existing[k]
        # quote values with spaces or special chars
        if any(c in v for c in " #\""):
            v = '"' + v.replace('"', '\\"') + '"'
        lines.append(f"{k}={v}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


# ---------- config.yaml ----------

def config_yaml_path(workspace: Path) -> Path:
    return workspace / "config.yaml"


def load_config(workspace: Path) -> AppConfig:
    path = config_yaml_path(workspace)
    if not path.exists():
        return AppConfig()
    if not _HAS_YAML:
        # very tiny fallback: only handles top-level scalars + channels list of dicts
        return _load_config_fallback(path)
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return AppConfig.from_dict(data)


def save_config(workspace: Path, cfg: AppConfig) -> None:
    path = config_yaml_path(workspace)
    path.parent.mkdir(parents=True, exist_ok=True)
    if _HAS_YAML:
        with path.open("w", encoding="utf-8") as f:
            yaml.safe_dump(cfg.to_dict(), f, allow_unicode=True, sort_keys=False)
    else:
        _save_config_fallback(path, cfg)


def _load_config_fallback(path: Path) -> AppConfig:
    """Minimal hand-rolled YAML-ish loader good enough for our config schema."""
    import json
    data: dict = {}
    # If user hasn't installed pyyaml, we'd be brittle. Encourage pyyaml.
    raise RuntimeError(
        "PyYAML not installed. Run: pip install pyyaml"
    )


def _save_config_fallback(path: Path, cfg: AppConfig) -> None:
    raise RuntimeError(
        "PyYAML not installed. Run: pip install pyyaml"
    )


# ---------- helpers ----------

def ensure_workspace(workspace: Path) -> None:
    """Create workspace + minimal files if missing."""
    workspace.mkdir(parents=True, exist_ok=True)
    for fname in ("SOUL.md", "IDENTITY.md", "USER.md", "MEMORY.md"):
        p = workspace / fname
        if not p.exists():
            p.write_text(f"# {fname[:-3]}\n\nTODO: 写点东西。\n", encoding="utf-8")
    (workspace / "skills").mkdir(exist_ok=True)
    (workspace / "logs").mkdir(exist_ok=True)
    env_path = workspace / ".env"
    if not env_path.exists():
        env_path.write_text(
            "# Secrets live here. NEVER commit this file.\n"
            "OPENAI_API_KEY=\n"
            "OPENAI_BASE_URL=https://api.openai.com/v1\n"
            "OPENAI_MODEL=gpt-4o-mini\n",
            encoding="utf-8",
        )